namespace LightweightObjectMapper;

internal class Constants
{
    #region Public 字段

    public const string CodeFileHeader = @"// <Auto-Generated/>

#pragma warning disable IDE0005
#pragma warning disable CS0105

";

    public const string GenerateNestedClassName = "Generated";

    public const string MapMethodName = "MapTo";

    public const string PreCodesFileName = "LightweightObjectMapperPreCodes.cs";

    public const string PredefinedSpecialTypeMappingFileName = "PredefinedSpecialTypeMapping.cs";

    public const string RootNamespace = "LightweightObjectMapper";

    #region MethodNamePrefix

    public const string CollectionMappingMethodNamePrefix = "CollectionMapping_";
    public const string MappingPrepareMethodNamePrefix = "MappingPrepare_";
    public const string PostMappingMethodNamePrefix = "PostMapping_";
    public const string TypeMappingMethodNamePrefix = "TypeMapping_";

    #endregion MethodNamePrefix

    #endregion Public 字段
}
