//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightweightObjectMapper.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightweightObjectMapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 LightweightObjectMapper must has a specific type to generate code. &quot;{0}&quot; is not a supported type. 的本地化字符串。
        /// </summary>
        internal static string AmbiguousMapTypeDiagnosticMessage {
            get {
                return ResourceManager.GetString("AmbiguousMapTypeDiagnosticMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There must be a clear target type. 的本地化字符串。
        /// </summary>
        internal static string AmbiguousMapTypeDiagnosticTitle {
            get {
                return ResourceManager.GetString("AmbiguousMapTypeDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not use a instance of &quot;{0}&quot; to do collection map. Please using generic method. 的本地化字符串。
        /// </summary>
        internal static string CollectionMapIncorrectUsageMessage {
            get {
                return ResourceManager.GetString("CollectionMapIncorrectUsageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection map incorrect usage. 的本地化字符串。
        /// </summary>
        internal static string CollectionMapIncorrectUsageTitle {
            get {
                return ResourceManager.GetString("CollectionMapIncorrectUsageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The collection mapping method should contain the unique generic parameter &quot;T&quot; and the unique parameter &quot;IEnumerable {T}&quot;, and the return type should be the derived type of &quot;IEnumerable {T}&quot; 的本地化字符串。
        /// </summary>
        internal static string CollectionMappingMethodDefineErrorMessage {
            get {
                return ResourceManager.GetString("CollectionMappingMethodDefineErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection mapping method define error. 的本地化字符串。
        /// </summary>
        internal static string CollectionMappingMethodDefineErrorTitle {
            get {
                return ResourceManager.GetString("CollectionMappingMethodDefineErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructor match failed on &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ConstructorMatchFailedMessage {
            get {
                return ResourceManager.GetString("ConstructorMatchFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructor match failed. 的本地化字符串。
        /// </summary>
        internal static string ConstructorMatchFailedTitle {
            get {
                return ResourceManager.GetString("ConstructorMatchFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate definition for collection \&quot;{0}\&quot; mapping. 的本地化字符串。
        /// </summary>
        internal static string DuplicateDefinitionCollectionMappingMethodMessage {
            get {
                return ResourceManager.GetString("DuplicateDefinitionCollectionMappingMethodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate definition for collection mapping method. 的本地化字符串。
        /// </summary>
        internal static string DuplicateDefinitionCollectionMappingMethodTitle {
            get {
                return ResourceManager.GetString("DuplicateDefinitionCollectionMappingMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use the placeholder extension class. 的本地化字符串。
        /// </summary>
        internal static string ErrorCallPlaceholderClassMessage {
            get {
                return ResourceManager.GetString("ErrorCallPlaceholderClassMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use the placeholder extension method. If not redirect to the right mapper extension method please try fix other errors and rebuild the project. 的本地化字符串。
        /// </summary>
        internal static string ErrorCallPlaceholderMethodMessage {
            get {
                return ResourceManager.GetString("ErrorCallPlaceholderMethodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error [MappingProfileInclude] tag. &quot;{0}&quot; is not a valid MappingProfile Class. 的本地化字符串。
        /// </summary>
        internal static string ErrorMappingProfileIncludeMessage {
            get {
                return ResourceManager.GetString("ErrorMappingProfileIncludeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error [MappingProfileInclude] tag. 的本地化字符串。
        /// </summary>
        internal static string ErrorMappingProfileIncludeTitle {
            get {
                return ResourceManager.GetString("ErrorMappingProfileIncludeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intance for class &quot;{0}&quot; has init only property witch can not map - &quot;{1}&quot; . 的本地化字符串。
        /// </summary>
        internal static string InitOnlyPropertyCanNotMapMessage {
            get {
                return ResourceManager.GetString("InitOnlyPropertyCanNotMapMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance&apos;s init only property can not map. 的本地化字符串。
        /// </summary>
        internal static string InitOnlyPropertyCanNotMapTitle {
            get {
                return ResourceManager.GetString("InitOnlyPropertyCanNotMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need partial keyword for type define &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string NeedPartialKeywordMessage {
            get {
                return ResourceManager.GetString("NeedPartialKeywordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need partial keyword. 的本地化字符串。
        /// </summary>
        internal static string NeedPartialKeywordTitle {
            get {
                return ResourceManager.GetString("NeedPartialKeywordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class &quot;{0}&quot; has no public constructor. 的本地化字符串。
        /// </summary>
        internal static string NoAnyPublicConstructorMessage {
            get {
                return ResourceManager.GetString("NoAnyPublicConstructorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class must has public constructor. 的本地化字符串。
        /// </summary>
        internal static string NoAnyPublicConstructorTitle {
            get {
                return ResourceManager.GetString("NoAnyPublicConstructorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property or field - &quot;{0}&quot; has not found map item. 的本地化字符串。
        /// </summary>
        internal static string NotFoundMatchPropertyOrFieldMessage {
            get {
                return ResourceManager.GetString("NotFoundMatchPropertyOrFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property or field has not found map item. 的本地化字符串。
        /// </summary>
        internal static string NotFoundMatchPropertyOrFieldTitle {
            get {
                return ResourceManager.GetString("NotFoundMatchPropertyOrFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property or field - &quot;{0}&quot; has found map item. But type not match {1} -&gt; {2}. 的本地化字符串。
        /// </summary>
        internal static string PropertyOrFieldTypeNotMatchMessage {
            get {
                return ResourceManager.GetString("PropertyOrFieldTypeNotMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property or field has found map item. But type not match. 的本地化字符串。
        /// </summary>
        internal static string PropertyOrFieldTypeNotMatchTitle {
            get {
                return ResourceManager.GetString("PropertyOrFieldTypeNotMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intance for class &quot;{0}&quot; has read only field witch can not map - &quot;{1}&quot; . 的本地化字符串。
        /// </summary>
        internal static string ReadOnlyFieldCanNotMapMessage {
            get {
                return ResourceManager.GetString("ReadOnlyFieldCanNotMapMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance&apos;s read only field can not map. 的本地化字符串。
        /// </summary>
        internal static string ReadOnlyFieldCanNotMapTitle {
            get {
                return ResourceManager.GetString("ReadOnlyFieldCanNotMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undefined collection mapping &apos;{0}&apos; -&gt;&apos;{1}&apos;, please try declaring it&apos;s mapping method using &apos;MappingProfile&apos;. 的本地化字符串。
        /// </summary>
        internal static string UndefinedCollectionMappingMessage {
            get {
                return ResourceManager.GetString("UndefinedCollectionMappingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undefined collection mapping. 的本地化字符串。
        /// </summary>
        internal static string UndefinedCollectionMappingTitle {
            get {
                return ResourceManager.GetString("UndefinedCollectionMappingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected exception while generate code. {0} 的本地化字符串。
        /// </summary>
        internal static string UnexpectedExceptionWhileBuildingMessage {
            get {
                return ResourceManager.GetString("UnexpectedExceptionWhileBuildingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected exception while generate code. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedExceptionWhileBuildingTitle {
            get {
                return ResourceManager.GetString("UnexpectedExceptionWhileBuildingTitle", resourceCulture);
            }
        }
    }
}
