// <Auto-Generated/>
using LightweightObjectMapper;

namespace MapperTestLibrary;

internal class ClassToStringClassSubClass
{
    public int Value { get; set; }

    public override string ToString()
    {
        return $"Value is {Value}";
    }
}

internal class ClassToStringClass1
{
    public ClassToStringClassSubClass Property1 { get; set; }
}

internal class ClassToStringClass2
{
    public string Property1 { get; set; }
}

file class Extensions
{
    public Extensions()
    {
        new ClassToStringClass1().MapTo<ClassToStringClass2>();
        new ClassToStringClass1().MapTo(new ClassToStringClass2());
        new ClassToStringClass2().MapTo<ClassToStringClass2>();
    }
}
