// <Auto-Generated/>
using LightweightObjectMapper;

namespace MapperTestLibrary;

internal class ClassToObjectClassSubClass
{
    public int Value { get; set; }
}

internal class ClassToObjectClass1
{
    public ClassToObjectClassSubClass Property1 { get; set; }
}

internal class ClassToObjectClass2
{
    public object Property1 { get; set; }
}

file class Extensions
{
    public Extensions()
    {
        new ClassToObjectClass1().MapTo<ClassToObjectClass2>();
        new ClassToObjectClass1().MapTo(new ClassToObjectClass2());
        new ClassToObjectClass2().MapTo<ClassToObjectClass2>();
    }
}
