// <Auto-Generated/>
using System.Collections.Generic;
using LightweightObjectMapper;

namespace MapperTestLibrary;

internal record InnerNestedCollectionMapRecord1(int Property1, double Property2)
{
}

internal record NestedCollectionMapRecord1(int Property1, List<InnerNestedCollectionMapRecord1> Items)
{
}

internal record InnerNestedCollectionMapRecord2(int Property1, double Property2)
{
}

internal record NestedCollectionMapRecord2(int Property1, IEnumerable<InnerNestedCollectionMapRecord2> Items)
{
}


file class Extensions
{
    public Extensions()
    {
        new InnerNestedCollectionMapRecord1(default, default).MapTo<InnerNestedCollectionMapRecord2>();
        new NestedCollectionMapRecord1(default, default).MapTo<NestedCollectionMapRecord2>();
        new NestedCollectionMapRecord2(default, default).MapTo<NestedCollectionMapRecord2>();
    }
}
