// <Auto-Generated/>
using System.Collections.Generic;
using LightweightObjectMapper;

namespace MapperTestLibrary;

internal class SimpleValueListClass1
{
    public int[] Property1 { get; set; }

    public double[] Property2 { get; set; }

    public string[] Property3 { get; set; }

    public bool[] Property4 { get; set; }

    public int?[] Property5 { get; set; }

    public int?[] Property6 { get; set; }
}

internal class SimpleValueListClass2
{
    public List<int> Property1 { get; set; }

    public List<double> Property2 { get; set; }

    public List<string> Property3 { get; set; }

    public List<bool> Property4 { get; set; }

    public List<int?> Property5 { get; set; }

    public List<int?> Property6 { get; set; }
}

file class Extensions
{
    public Extensions()
    {
        new SimpleValueListClass1().MapTo<SimpleValueListClass2>();
        new SimpleValueListClass1().MapTo(new SimpleValueListClass2());
        new SimpleValueListClass2().MapTo<SimpleValueListClass2>();
    }
}
