// <Auto-Generated/>
using LightweightObjectMapper;

namespace MapperTestLibrary;

internal struct SimpleStructFieldMapStruct1
{
    public int Property1;

    public double Property2;

    public string Property3;

    public bool Property4;

    public int? Property5;

    public int? Property6;
}

internal struct SimpleStructFieldMapStruct2
{
    public int Property1;

    public double Property2;

    public string Property3;

    public bool Property4;

    public int? Property5;

    public int? Property6;
}

file class Extensions
{
    public Extensions()
    {
        new SimpleStructFieldMapStruct1().MapTo<SimpleStructFieldMapStruct2>();
        var struct2 = new SimpleStructFieldMapStruct2();
        new SimpleStructFieldMapStruct1().MapTo(ref struct2);
        new SimpleStructFieldMapStruct2().MapTo<SimpleStructFieldMapStruct2>();
        var struct1 = new SimpleStructFieldMapStruct1();
        new SimpleStructFieldMapStruct1().MapTo(ref struct1);
    }
}
