// <Auto-Generated/>
using LightweightObjectMapper;

namespace MapperTestLibrary;

internal struct SimpleStructMapStruct1
{
    public int Property1 { get; set; }

    public double Property2 { get; set; }

    public string Property3 { get; set; }

    public bool Property4 { get; set; }

    public int? Property5 { get; set; }

    public int? Property6 { get; set; }
}

internal struct SimpleStructMapStruct2
{
    public int Property1 { get; set; }

    public double Property2 { get; set; }

    public string Property3 { get; set; }

    public bool Property4 { get; set; }

    public int? Property5 { get; set; }

    public int? Property6 { get; set; }
}

file class Extensions
{
    public Extensions()
    {
        new SimpleStructMapStruct1().MapTo<SimpleStructMapStruct2>();
        var struct2 = new SimpleStructMapStruct2();
        new SimpleStructMapStruct1().MapTo(ref struct2);
        new SimpleStructMapStruct2().MapTo<SimpleStructMapStruct2>();
        var struct1 = new SimpleStructMapStruct1();
        new SimpleStructMapStruct1().MapTo(ref struct1);
    }
}
