// <Auto-Generated/>
using System.Collections.Generic;
using LightweightObjectMapper;

namespace MapperTestLibrary;

internal class SimpleClassCollectionMapClass1
{
    public int Property1 { get; set; }

    public double Property2 { get; set; }

    public string Property3 { get; set; }

    public bool Property4 { get; set; }

    public int? Property5 { get; set; }

    public int? Property6 { get; set; }
}

internal class SimpleClassCollectionMapClass2
{
    public int Property1 { get; set; }

    public double Property2 { get; set; }

    public string Property3 { get; set; }

    public bool Property4 { get; set; }

    public int? Property5 { get; set; }

    public int? Property6 { get; set; }
}

file class Extensions
{
    public Extensions()
    {
        new List<SimpleClassCollectionMapClass1>().MapTo<IEnumerable<SimpleClassCollectionMapClass2>>();
        new List<SimpleClassCollectionMapClass1>().MapTo<List<SimpleClassCollectionMapClass2>>();
        new List<SimpleClassCollectionMapClass2>().MapTo<IEnumerable<SimpleClassCollectionMapClass2>>();
    }
}
