// <Auto-Generated/>
using LightweightObjectMapper;

namespace MapperTestLibrary;

internal class SimpleClassFieldMapClass1
{
    public int Property1;

    public double Property2;

    public string Property3;

    public bool Property4;

    public int? Property5;

    public int? Property6;
}

internal class SimpleClassFieldMapClass2
{
    public int Property1;

    public double Property2;

    public string Property3;

    public bool Property4;

    public int? Property5;

    public int? Property6;
}

file class Extensions
{
    public Extensions()
    {
        new SimpleClassFieldMapClass1().MapTo<SimpleClassFieldMapClass2>();
        new SimpleClassFieldMapClass1().MapTo(new SimpleClassFieldMapClass2());
        new SimpleClassFieldMapClass2().MapTo<SimpleClassFieldMapClass2>();
    }
}
