// <Auto-Generated/>
using LightweightObjectMapper;

namespace MapperTestLibrary;

internal class SimpleClassMapClass1
{
    public int Property1 { get; set; }

    public double Property2 { get; set; }

    public string Property3 { get; set; }

    public bool Property4 { get; set; }

    public int? Property5 { get; set; }

    public int? Property6 { get; set; }
}

internal class SimpleClassMapClass2
{
    public int Property1 { get; set; }

    public double Property2 { get; set; }

    public string Property3 { get; set; }

    public bool Property4 { get; set; }

    public int? Property5 { get; set; }

    public int? Property6 { get; set; }
}

file class Extensions
{
    public Extensions()
    {
        new SimpleClassMapClass1().MapTo<SimpleClassMapClass2>();
        new SimpleClassMapClass1().MapTo(new SimpleClassMapClass2());
        new SimpleClassMapClass2().MapTo<SimpleClassMapClass2>();
    }
}
