// <Auto-Generated/>
using LightweightObjectMapper;

namespace MapperTestLibrary;

internal class ValueTypeToStringClass1
{
    public int Property1 { get; set; }

    public double Property2 { get; set; }

    public decimal Property3 { get; set; }

    public bool Property4 { get; set; }

    public int? Property5 { get; set; }

    public int? Property6 { get; set; }
}

internal class ValueTypeToStringClass2
{
    public string Property1 { get; set; }

    public string Property2 { get; set; }

    public string Property3 { get; set; }

    public string Property4 { get; set; }

    public string Property5 { get; set; }

    public string Property6 { get; set; }
}

file class Extensions
{
    public Extensions()
    {
        new ValueTypeToStringClass1().MapTo<ValueTypeToStringClass2>();
        new ValueTypeToStringClass1().MapTo(new ValueTypeToStringClass2());
        new ValueTypeToStringClass2().MapTo<ValueTypeToStringClass2>();
    }
}
